import { ZurgBanner } from '@/components/ZurgBanner';
import {
	useAllDebridApiKey,
	useDebridLogin,
	usePremiumizeCredential,
	useRealDebridAccessToken,
	useTorBoxAccessToken,
} from '@/hooks/auth';
import { TORBOX_REFERRAL_URL } from '@/utils/referrals';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function StartPage() {
	const router = useRouter();
	const { loginWithRealDebrid, loginWithAllDebrid, loginWithTorbox, loginWithPremiumize } =
		useDebridLogin();
	const [rdToken] = useRealDebridAccessToken();
	const adKey = useAllDebridApiKey();
	const tbKey = useTorBoxAccessToken();
	const pmKey = usePremiumizeCredential();

	// Redirect to index if already logged in
	useEffect(() => {
		const isLoggedIn = rdToken || adKey || tbKey || pmKey;
		if (isLoggedIn) {
			router.push('/');
		}
	}, [rdToken, adKey, tbKey, pmKey, router]);

	return (
		<div className="flex min-h-screen flex-col items-center justify-center p-4">
			<Head>
				<title>Debrid Media Manager - Home</title>
				<meta name="robots" content="index, nofollow" />
			</Head>
			{/* logo generated by ChatGPT4 */}
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="200"
				height="200"
				viewBox="0 0 200 200"
				className="shrink-0"
			>
				<rect x="25" y="25" width="150" height="150" fill="#2C3E50" rx="20" ry="20" />
				<circle cx="100" cy="100" r="60" fill="#00A0B0" />
				<path d="M85,65 L85,135 L135,100 Z" fill="#ECF0F1" />
				<path d="M60,90 Q80,60 100,90 T140,90" fill="#CC333F" />
				<path
					d="M75,121 L80,151 L90,136 L100,151 L110,136 L120,151 L125,121 Z"
					fill="#EDC951"
				/>
			</svg>

			{/* SEO Text */}
			<div className="my-8 text-center">
				<h1 className="mb-4 text-xl font-bold">Welcome to Debrid Media Manager</h1>
				<p className="text-lg">
					Start building your movie and TV show library with truly unlimited storage size
				</p>
				<br />
				<a
					target="_blank"
					href="https://github.com/debridmediamanager/debrid-media-manager"
					className="text-lg underline decoration-dotted"
				>
					This website is open source and you can also run this on your own machine
				</a>
			</div>

			<ZurgBanner />

			{/* Login Buttons */}
			<div className="flex flex-col items-center">
				<p className="text-sm">Please login with one of the supported services below</p>
				{/* RealDebrid */}
				<div className="flex flex-row">
					<button
						className="m-2 rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
						onClick={loginWithRealDebrid}
					>
						Login with Real Debrid
					</button>
					<a
						className="m-2 rounded bg-green-500 px-4 py-2 text-white hover:bg-green-600"
						href="http://real-debrid.com/?id=11137529"
						target="_blank"
						rel="noopener noreferrer"
					>
						Create an account with RealDebrid
					</a>
				</div>

				{/* AllDebrid */}
				<div className="flex flex-row">
					<button
						className="m-2 rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
						onClick={loginWithAllDebrid}
					>
						Login with AllDebrid
					</button>
					<a
						className="m-2 rounded bg-green-500 px-4 py-2 text-white hover:bg-green-600"
						href="https://alldebrid.com/?uid=1kk5i&lang=en"
						target="_blank"
						rel="noopener noreferrer"
					>
						Create an account with AllDebrid
					</a>
				</div>

				{/* Torbox */}
				<div className="flex flex-row">
					<button
						className="m-2 rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
						onClick={loginWithTorbox}
					>
						Login with Torbox
					</button>
					<a
						className="m-2 rounded bg-green-500 px-4 py-2 text-white hover:bg-green-600"
						href={TORBOX_REFERRAL_URL}
						target="_blank"
						rel="noopener noreferrer"
					>
						Create an account with Torbox
					</a>
				</div>

				{/* Premiumize */}
				<div className="flex flex-row">
					<button
						className="m-2 rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
						onClick={loginWithPremiumize}
					>
						Login with Premiumize
					</button>
					<a
						className="m-2 rounded bg-green-500 px-4 py-2 text-white hover:bg-green-600"
						href="https://www.premiumize.me/"
						target="_blank"
						rel="noopener noreferrer"
					>
						Create an account with Premiumize
					</a>
				</div>

				<h2 className="text-l mb-2 mt-2 font-bold text-slate-500">Data Storage Policy</h2>
				<p className="flex-row text-center text-sm text-slate-500">
					Please note that no data or logs are stored on our servers
					<br />
					You can inspect every request if you want
					<br />
					Everything is stored on your browser&apos;s local storage
				</p>
			</div>
		</div>
	);
}
