import { useDebridLogin } from '@/hooks/auth';

export default function StartPage() {
	const { loginWithRealDebrid } = useDebridLogin();

	return (
		<div className="flex flex-col items-center justify-center h-screen">
			{/* logo generated by ChatGPT4 */}
			<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">
				<rect x="25" y="25" width="150" height="150" fill="#2C3E50" rx="20" ry="20" />
				<circle cx="100" cy="100" r="60" fill="#00A0B0" />
				<path d="M85,65 L85,135 L135,100 Z" fill="#ECF0F1" />
				<path d="M60,90 Q80,60 100,90 T140,90" fill="#CC333F" />
				<path
					d="M75,121 L80,151 L90,136 L100,151 L110,136 L120,151 L125,121 Z"
					fill="#EDC951"
				/>
			</svg>

			{/* SEO Text */}
			<div className="my-8 text-center">
				<h1 className="text-3xl font-bold mb-4">Welcome to Debrid Media Manager</h1>
				<p className="text-lg">The media collection with truly unlimited storage size</p>
				<a
					target="_blank"
					href="https://docs.google.com/document/d/13enrfVXcGEEd0Yqb0PBTpGYrIvQpSfeIaAMZ_LiBDzM/edit?usp=sharing"
					className="text-lg underline decoration-dotted"
				>
					Check our how to/recommended setup here
				</a>
			</div>

			{/* Login Buttons */}
			<div className="flex flex-col items-center">
				<p className="text-sm">
					Please login with one of the supported Debrid services below
				</p>
				{/* RealDebrid */}
				<div className="flex flex-row">
					<button
						className="px-4 py-2 m-2 text-white bg-blue-500 rounded hover:bg-blue-600"
						onClick={loginWithRealDebrid}
					>
						Login with Real Debrid
					</button>
					<a
						className="px-4 py-2 m-2 text-white bg-green-500 rounded hover:bg-green-600"
						href="http://real-debrid.com/?id=440161"
						target="_blank"
						rel="noopener noreferrer"
					>
						Create an account with RealDebrid
					</a>
				</div>

				{/* AllDebrid */}
				<div className="flex flex-row">
					<button
						className="px-4 py-2 m-2 text-white bg-blue-500 disabled:opacity-50 disabled:bg-gray-500 rounded hover:bg-blue-600"
						disabled
						title="Coming soon!"
					>
						Login with AllDebrid
					</button>
					<a
						className="px-4 py-2 m-2 text-white bg-gray-500 opacity-50 rounded"
						href="https://alldebrid.com/?uid=1kk5i&lang=en"
						target="_blank"
						rel="noopener noreferrer"
					>
						Create an account with AllDebrid
					</a>
				</div>

				<h2 className="text-l text-slate-500 font-bold mt-2 mb-2">Data Storage Policy</h2>
				<p className="text-sm text-slate-500 flex-row text-center">
					Please note that no data or logs are stored on our servers
					<br />
					You can inspect every request if you want
					<br />
					Everything is stored on your browser&apos;s local storage
					<br />
					We use corsproxy.org to bypass RealDebrid API&apos;s CORS restrictions
				</p>
			</div>
		</div>
	);
}
